apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-crm-cert
  namespace: default
spec:
  dnsNames:
    - adam-democrm.myddns.me
  secretName: demo-crm-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer