apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm-deployment
  labels:
    app: demo-crm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
      - name: demo-crm
        image: gcr.io/kubernetes-bootcamp-365905/adam_demo-crm:latest
        ports:
        - containerPort: 3000
        env:
        - name: USER
          value: "root"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        - name: MONGODB_URI
          value: "mongodb://$(USER):$(PASSWORD)@mongodb-0.mongodb-headless:27017"
        - name: LOG_LEVEL
          value: "info"
        - name: PERSISTENCE
          value: "true"
        