apiVersion: v1
kind: Secret
metadata:
  name: secret-env
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6TzkwRTRuTWt0NUBtb25nb2RiLTAubW9uZ29kYi1oZWFkbGVzczoyNzAxNw==
  NEWS_API_KEY: NTRkNWQ4MWUwYWYyNDZjNWI4MTNlZjU1ZWNkYmYwYWI=
  RABBITMQ_URI: YW1xcDovL3VzZXI6M0FKN3pnOTdXcEFOOFZNQ0ByYWJiaXRtcS0wLnJhYmJpdG1xLWhlYWRsZXNzOjU2NzI=
  LOG_LEVEL: aW5mbw==
  PERSISTENCE: dHJ1ZQ==