apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: default
  # annotations:
  #   "helm.sh/hook": post-install
  #   "helm.sh/hook-weight": "1"
  #   "helm.sh/hook-delete-policy": hook-succeeded
  #   "app.kubernetes.io/managed-by": Helm
  #   "meta.helm.sh/release-name": adam-helm-repo
  #   "meta.helm.sh/release-namespace": default
spec:
  acme:
    server: {{ .Values.clusterIssuer.server }}
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: {{ .Values.clusterIssuer.ingressClass }}