apiVersion: v1
kind: Service
metadata:
  name: demo-crm-service
  labels:
    app: demo-crm
spec:
  {{ if .Values.ingress.enabled }}
  type: {{ .Values.service.type }}
  {{- else -}}
  type: {{ .Values.service.loadbalancer }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: demo-crm
