{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-data-remover
  namespace: default
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-data-remover
            image: {{ .Values.cronjob.image }}
            env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_ROOT_USER
            - name: PWD
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_ROOT_PASSWORD
            command: ["/bin/sh","-c"]
            args:
            - mongosh --host "adam-helm-repo-mongodb-0.adam-helm-repo-mongodb-headless" --username "$(USER)" -p "$(PWD)" --eval "db.clients.deleteMany( {} )"
          restartPolicy: OnFailure
{{- end }}